services:
  postgres:
    image: postgres:15
    container_name: actly_postgres
    environment:
      POSTGRES_DB: volunteerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: actly_app_mypassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./Actly.API
    container_name: actly_api
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5127:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  frontend:
    build:
      context: ./Actly.Client
    container_name: actly_frontend
    ports:
      - "4201:80"
    depends_on:
      - api

volumes:
  postgres_data:
